package com.example.WGR_hibernate6.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.Parameter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * StatusDir generated by hbm2java
 */

@Entity
@Table(name = "status_dir")
public class StatusDir implements Serializable {


	@Id
	@org.hibernate.annotations.GenericGenerator(
			name = "ID_GENERATOR_STATUS_DIR",
			type = org.hibernate.id.enhanced.SequenceStyleGenerator.class,
			parameters = {
					@Parameter(name = "sequence_name", value = "STATUS_DIR_HID"),
					@Parameter(name = "initial_value", value = "1")
			}
	)
	private BigDecimal hid;
	private String name;
	private String prim;
    private String nameDe;
    private String primDe;
	private String nameEn;
	private String primEn;
	private String namePl;
	private String primPl;
	private String nameZhCn;
	private String primZhCn;
	private String type;
	private Byte priority;

	public Byte getPriority() {
		return priority;
	}

	public void setPriority(Byte priority) {
		this.priority = priority;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPrimDe() {
        return primDe;
    }

    public void setPrimDe(String primDe) {
        this.primDe = primDe;
    }

    public String getNameDe() {
        return nameDe;
    }

    public void setNameDe(String nameDe) {
        this.nameDe = nameDe;
    }

    public StatusDir() {
	}

	public StatusDir(BigDecimal hid) {
		this.hid = hid;
	}

	public StatusDir(BigDecimal hid, String name, String prim,  String nameDe, String primDE) {
		this.hid = hid;
		this.name = name;
		this.prim = prim;
        this.nameDe = nameDe;
        this.primDe = primDE;
	}

	public BigDecimal getHid() {
		return this.hid;
	}

	public void setHid(BigDecimal hid) {
		this.hid = hid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}


	public String getNameEn() {
		return nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getPrimEn() {
		return primEn;
	}

	public void setPrimEn(String primEn) {
		this.primEn = primEn;
	}

	public String getNamePl() {
		return namePl;
	}

	public void setNamePl(String namePl) {
		this.namePl = namePl;
	}

	public String getPrimPl() {
		return primPl;
	}

	public void setPrimPl(String primPl) {
		this.primPl = primPl;
	}

	public String getNameZhCn() {
		return nameZhCn;
	}

	public void setNameZhCn(String nameZhCn) {
		this.nameZhCn = nameZhCn;
	}

	public String getPrimZhCn() {
		return primZhCn;
	}

	public void setPrimZhCn(String primZhCn) {
		this.primZhCn = primZhCn;
	}

	public String getNameByLang(String lang) {
    	switch (lang) {
//			case "ru": return this.name;
			case "en": return this.nameEn;
			case "de": return this.nameDe;
			case "pl": return this.namePl;
			case "zh_CN": return this.nameZhCn;
			default: return this.name;
		}
	}
}
