package com.example.WGR_hibernate6.model;

// Generated 12.11.2010 16:44:31 by Hibernate Tools 3.4.0.Beta1

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;

/**
 * UsrPrivilegsDir generated by hbm2java
 */
@Entity
@Table(name = "usr_privilegs_dir")
public class UsrPrivilegsDir implements Serializable {

	@Id
	private String name;
	private String descr;
	private boolean locked;
	private Date dattr;
	private String un;
    private boolean hidden;

    public boolean isHidden() {
        return hidden;
    }

    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    public UsrPrivilegsDir() {
	}
	
	public UsrPrivilegsDir(String name) {
		this.name = name;
	}

	public UsrPrivilegsDir(String name, boolean locked, Date dattr, String un) {
		this.name = name;
		this.locked = locked;
		this.dattr = dattr;
		this.un = un;
	}

	public UsrPrivilegsDir(String name, String descr, boolean locked, Date dattr, String un) {
		this.name = name;
		this.descr = descr;
		this.locked = locked;
		this.dattr = dattr;
		this.un = un;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public Date getDattr() {
		return this.dattr;
	}

	public void setDattr(Date dattr) {
		this.dattr = dattr;
	}

	public String getUn() {
		return this.un;
	}

	public void setUn(String un) {
		this.un = un;
	}

}
